name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

  pull_request:

  workflow_dispatch:

  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare Theos
      uses: waruhachi/theos-action@v2.4.6
      with:
        theos-src: roothide/theos
        theos-branch: master
        sdks-src: xybp888/iOS-SDKs
        sdks-branch: master
        libgcuniversal: 'false'
        altlist: 'false'

    - name: Prepare AltList
      run: |
        git clone https://github.com/opa334/AltList.git
        cd AltList
        chmod +x install_to_theos.sh
        ARCHS="arm64 arm64e" ./install_to_theos.sh
        mkdir -p $THEOS/include/AltList
        cp AltList.h $THEOS/include/AltList/
        cd ..

    - name: Patch PSSpecifier
      run: |
        sed -i '' 's/SEL action;/SEL action;\n\tSEL setter;\n\tSEL getter;/' $THEOS/vendor/include/Preferences/PSSpecifier.h

    - name: Build package
      run: |
        rm -f packages/*
        ARCHS="arm64 arm64e" make package-all

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: packages/*.deb
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/packages/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
